### ISSUE TITLE
WordPress 5.0 & Yoast compatibility - RC 1.1

### ISSUE THREAD

**Issue by moorscode** [gravityforms/gravityblocks#8]
### Please give us a description of what happened.
Blank meta box when using Yoast SEO Premium with Gravity Forms and the Gravity Forms Gutenberg add-on.

### Please describe what you expected to happen and why.
No error and meta box works.

### How can we reproduce this behavior?
1. Install and activate plugins
2. Go to Posts > Add New
3. See error in console

#### Used versions
* WordPress version: 5.0 (or 4.9.8 + Gutenberg plugin)
* Yoast SEO version: 9.2.1 (premium only)
* Relevant plugins in case of a bug: Gravity Forms v2.4.2 & [Gravity Forms Gutenberg Add-On v1.0-rc-1.1](https://github.com/gravityforms/gravityblocks/)
* Tested with theme: Twenty Nineteen

### Extras
Asked customer to report the issue to Gravity Forms as well.

![selection_307](https://user-images.githubusercontent.com/8060612/49777221-d573fe00-fcbc-11e8-8d49-9d75fe794c7d.png)
![selection_308](https://user-images.githubusercontent.com/8060612/49777223-da38b200-fcbc-11e8-94d1-43ae0d82d2ba.png)

Original issue: https://github.com/Yoast/wordpress-seo-premium/issues/2172

**Comment by travislopes** [comment]
This was resolved in a Gravity Forms release.
